-- Discard-timing model fitted to your own opponents.
--
-- Generated by fit-timing.py from __FIT_SUMMARY__.
-- Do not copy someone else's copy of this file: the whole point is that
-- these constants differ between people. See docs/03-fitting-a-delay-model.md.
--
-- Akagi calls decide_delay(ctx) and expects
--   { delay_ms = <number>, allow_bank = <bool> }
-- where delay_ms is the target TOTAL time between the server offering the
-- decision and receiving the action — not a sleep length. Akagi subtracts
-- whatever the network and bot inference already spent, then enforces
-- min_delay_ms and the budget caps on top.
--
-- The file hot-reloads on save. If it errors, Akagi falls back to its
-- built-in model and logs the reason once.

-- ---------------------------------------------------------------------------
-- Fitted parameters — log-normal { mu, sigma } in ln-seconds
-- ---------------------------------------------------------------------------
-- These are the MARGINAL distributions of what your opponents actually did,
-- measured end to end. That matters: because they are marginals, they already
-- contain every effect that made those players slow or fast — deep hands,
-- live riichi, awkward shapes. Adding conditional bonuses on top would count
-- the same thinking twice, which is exactly the flaw documented in
-- docs/03-fitting-a-delay-model.md. Resist the urge.

local TSUMOGIRI = { __MU_TSUMOGIRI__, __SIGMA_TSUMOGIRI__ }
local TEDASHI   = { __MU_TEDASHI__, __SIGMA_TEDASHI__ }
local OPENING   = { __MU_OPENING__, __SIGMA_OPENING__ }

-- The occasional genuine tank: recounting the discards, weighing a fold.
-- One log-normal alone cannot reach the tail real players produce — it
-- lands near 4% of discards at six seconds or longer where measurement
-- says closer to 7% — so a second component is mixed in at the rate that
-- reproduces your opponents' long-thought share. This is still fitting the
-- marginal, not bolting a bonus onto it.
local P_LONG = { tsumogiri = __P_LONG_TSUMOGIRI__, tedashi = __P_LONG_TEDASHI__ }
local LONG    = { 1.50, 0.50 }

-- Non-discard decisions cannot be fitted from logs: the wire shows an
-- opponent's call or riichi, but never when the window opened for them, so
-- there is no think time to measure. These are offsets from your fitted
-- hand-discard level, chosen by judgement rather than measurement — a call
-- window is answered faster than a discard is chosen, a riichi declaration
-- slower. Treat them as placeholders you may tune, not as findings.
local OFFSET = {
  reach           =  0.45,  -- riichi declaration
  claim           = -0.39,  -- chi / pon / kan / skip, i.e. the call window
  post_call_dahai = -0.13,  -- the discard right after your own call
  hora            = -0.50,  -- ron / tsumo
  in_riichi       = -0.30,  -- skipping while already in riichi
}

local function other(kind)
  return TEDASHI[1] + OFFSET[kind], math.max(TEDASHI[2] * 0.85, 0.25)
end

-- ---------------------------------------------------------------------------
-- Model
-- ---------------------------------------------------------------------------

function decide_delay(ctx)
  local think
  local allow_bank = false

  if ctx.in_riichi then
    -- In riichi only claim windows reach here; Mahjong Soul auto-discards
    -- the draws. Humans still glance rather than answering instantly.
    local mu, sigma = other("in_riichi")
    return { delay_ms = ctx.lognormal(mu, sigma) * 1000 }
  end

  if ctx.dealer_opening then
    -- The dealer's opening discard is its own regime, not an ordinary
    -- discard with a survey bonus added: fourteen unseen tiles get sorted
    -- rather than one draw being reacted to. Measured openings run several
    -- seconds slower than mid-hand discards and much wider.
    --
    -- The fitted median is normally above the server's free allowance, so
    -- the budget shaping below will unlock the bank here. That is correct
    -- and matches what human dealers do. If instead you model this as
    -- "normal discard, but slower", the draw stays under the free window,
    -- the bank never unlocks, and the soft cap flattens nearly every
    -- opening onto one value — a single whole-second bucket, which is the
    -- most identifiable thing a delay model can do. See
    -- docs/03-fitting-a-delay-model.md.
    think = ctx.lognormal(OPENING[1], OPENING[2])
  elseif ctx.action == "dahai" then
    if ctx.post_call then
      local mu, sigma = other("post_call_dahai")
      think = ctx.lognormal(mu, sigma)
    elseif ctx.tsumogiri then
      think = ctx.lognormal(TSUMOGIRI[1], TSUMOGIRI[2])
      if ctx.rng() < P_LONG.tsumogiri then
        think = think + ctx.lognormal(LONG[1], LONG[2])
        allow_bank = true
      end
    else
      think = ctx.lognormal(TEDASHI[1], TEDASHI[2])
      if ctx.rng() < P_LONG.tedashi then
        think = think + ctx.lognormal(LONG[1], LONG[2])
        allow_bank = true
      end
    end
  elseif ctx.action == "reach" then
    local mu, sigma = other("reach")
    think = ctx.lognormal(mu, sigma)
  elseif ctx.action == "hora" then
    local mu, sigma = other("hora")
    think = ctx.lognormal(mu, sigma)
  elseif ctx.action == "ankan" or ctx.action == "kakan" then
    think = ctx.lognormal(TEDASHI[1], TEDASHI[2])
  else
    local mu, sigma = other("claim")
    think = ctx.lognormal(mu, sigma)
  end

  -- ---------------------------------------------------------------------
  -- Budget shaping
  -- ---------------------------------------------------------------------
  -- The server grants fixed_ms per decision plus a bank (add_ms) that
  -- refills every kyoku. Exceeding the free window is ordinary play, not an
  -- emergency — real players dip into the bank regularly — so the bank is
  -- unlocked rather than the thought being truncated. But when the bank is
  -- nearly dry, humans wrap up instead of risking the auto-discard timer.
  if ctx.budget ~= nil then
    -- Floored at zero: a sub-second fixed_ms must degrade to "answer at the
    -- enforced minimum", not to a negative delay_ms, which Akagi rejects —
    -- and a rejected return silently disables this script for the session.
    local free_s = math.max(ctx.budget.fixed_ms / 1000 - 1.0, 0)
    local bank_s = ctx.budget.add_ms / 1000
    if think > free_s then
      if bank_s >= 3.0 then
        allow_bank = true
      else
        think = free_s
      end
    end
  end

  return { delay_ms = think * 1000, allow_bank = allow_bank }
end
